import { EmptyState, PageHeader, Surface } from "@/components/growth-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { Plus, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import { PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer } from "recharts";
import { toast } from "sonner";

export default function Skills() {
  const utils = trpc.useUtils(); const { data: skills } = trpc.growth.skills.list.useQuery(); const create = trpc.growth.skills.create.useMutation({ onSuccess: () => { utils.growth.skills.invalidate(); utils.growth.dashboard.invalidate(); toast.success("能力维度已添加"); setName(""); setCategory(""); } }); const [name, setName] = useState(""); const [category, setCategory] = useState(""); const [color, setColor] = useState("#6875F5");
  function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; create.mutate({ name: name.trim(), category: category || undefined, color }); }
  const chartData = skills?.slice(0, 8).map(skill => ({ subject: skill.name, value: Math.max(8, skill.progress), fullMark: 100 })) ?? [];
  return <div className="space-y-7"><PageHeader eyebrow="能力图谱" title="能力不是标签，而是可积累的证据。" description="将每一次任务完成和学习记录回流为经验值，展示更真实的能力成长轨迹。" /><div className="grid gap-5 xl:grid-cols-[0.72fr_1.28fr]"><Surface><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-primary" /><p className="font-semibold">新增能力维度</p></div><form className="mt-5 space-y-4" onSubmit={submit}><div><Label htmlFor="skill-name">技能名称</Label><Input id="skill-name" className="mt-2 rounded-xl" value={name} onChange={event => setName(event.target.value)} placeholder="例如：系统设计" /></div><div><Label htmlFor="skill-category">能力分类</Label><Input id="skill-category" className="mt-2 rounded-xl" value={category} onChange={event => setCategory(event.target.value)} placeholder="例如：工程能力" /></div><div><Label htmlFor="skill-color">识别颜色</Label><div className="mt-2 flex gap-2"><input id="skill-color" className="h-10 w-12 rounded-xl border border-input bg-background p-1" type="color" value={color} onChange={event => setColor(event.target.value)} /><Input className="rounded-xl" value={color} onChange={event => setColor(event.target.value)} /></div></div><Button type="submit" className="w-full rounded-xl"><Plus className="mr-2 h-4 w-4" />添加能力</Button></form><p className="mt-5 rounded-xl bg-muted/45 p-3 text-xs leading-5 text-muted-foreground">完成关联技能的任务、学习记录后，系统会自动创建经验事件并累计到对应能力。</p></Surface><div className="space-y-5"><Surface><div className="flex items-center justify-between"><div><p className="font-semibold">能力雷达</p><p className="mt-1 text-sm text-muted-foreground">依据已积累的真实经验值计算，不使用虚构评分。</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">{skills?.length ?? 0} 个维度</span></div>{chartData.length >= 3 ? <div className="mt-2 h-72"><ResponsiveContainer width="100%" height="100%"><RadarChart data={chartData} outerRadius="72%"><PolarGrid stroke="currentColor" opacity={0.13} /><PolarAngleAxis dataKey="subject" tick={{ fill: "currentColor", fontSize: 12 }} /><Radar dataKey="value" stroke="#6875F5" fill="#6875F5" fillOpacity={0.22} /></RadarChart></ResponsiveContainer></div> : <div className="mt-5"><EmptyState title="至少添加 3 个能力维度" body="雷达图将在拥有足够的能力坐标后展示，这些维度会随着真实行动持续变化。" /></div>}</Surface><Surface><p className="font-semibold">经验明细</p><div className="mt-5 space-y-4">{skills?.length ? skills.map(skill => <div key={skill.id}><div className="mb-2 flex items-center justify-between"><div><span className="text-sm font-medium">{skill.name}</span><span className="ml-2 text-xs text-muted-foreground">{skill.category} · Lv.{skill.level}</span></div><span className="text-xs font-medium text-primary">{skill.experience} XP</span></div><Progress value={skill.progress} className="h-2" /></div>) : <p className="py-10 text-center text-sm text-muted-foreground">添加第一项能力，让成长拥有可被看见的坐标。</p>}</div></Surface></div></div></div>;
}
